# Server configuration
# If this port has a conflict, change it here
server.port=8083

# Logging configuration
logging.level.root=INFO
logging.level.com.cognizant.springlearn=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
